[package]
name = "rust-resolution-w1"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.13", features = ["json", "blocking"] }
serde = { version = "1.0.228", features = ["derive"] }
color-eyre = "0.6.3"
crossterm = "0.29.0"
ratatui = "0.30.0"
tui = "0.19.0"
serde_json = "1.0.149"
dirs = "6.0.0"
chrono = "0.4.44"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
